//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Controls.LocalizedResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Controls.LocalizedResources.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 约 1 分钟前 的本地化字符串。
        /// </summary>
        public static string AboutAMinuteAgo {
            get {
                return ResourceManager.GetString("AboutAMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 约 1 个月前 的本地化字符串。
        /// </summary>
        public static string AboutAMonthAgo {
            get {
                return ResourceManager.GetString("AboutAMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 约 1 小时前 的本地化字符串。
        /// </summary>
        public static string AboutAnHourAgo {
            get {
                return ResourceManager.GetString("AboutAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 约 1 周前 的本地化字符串。
        /// </summary>
        public static string AboutAWeekAgo {
            get {
                return ResourceManager.GetString("AboutAWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闹钟重复时间 的本地化字符串。
        /// </summary>
        public static string AlarmRepeatsOn {
            get {
                return ResourceManager.GetString("AlarmRepeatsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节 的本地化字符串。
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择日期 的本地化字符串。
        /// </summary>
        public static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string DateTimePickerCancelText {
            get {
                return ResourceManager.GetString("DateTimePickerCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string DateTimePickerDoneText {
            get {
                return ResourceManager.GetString("DateTimePickerDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB 的本地化字符串。
        /// </summary>
        public static string Gigabyte {
            get {
                return ResourceManager.GetString("Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KB 的本地化字符串。
        /// </summary>
        public static string Kilobyte {
            get {
                return ResourceManager.GetString("Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上星期五 的本地化字符串。
        /// </summary>
        public static string last_Friday {
            get {
                return ResourceManager.GetString("last Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上个星期一 的本地化字符串。
        /// </summary>
        public static string last_Monday {
            get {
                return ResourceManager.GetString("last Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上星期六 的本地化字符串。
        /// </summary>
        public static string last_Saturday {
            get {
                return ResourceManager.GetString("last Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上个星期日 的本地化字符串。
        /// </summary>
        public static string last_Sunday {
            get {
                return ResourceManager.GetString("last Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上星期四 的本地化字符串。
        /// </summary>
        public static string last_Thursday {
            get {
                return ResourceManager.GetString("last Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上星期二 的本地化字符串。
        /// </summary>
        public static string last_Tuesday {
            get {
                return ResourceManager.GetString("last Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上星期三 的本地化字符串。
        /// </summary>
        public static string last_Wednesday {
            get {
                return ResourceManager.GetString("last Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MB 的本地化字符串。
        /// </summary>
        public static string Megabyte {
            get {
                return ResourceManager.GetString("Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期五 的本地化字符串。
        /// </summary>
        public static string on_Friday {
            get {
                return ResourceManager.GetString("on Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期一 的本地化字符串。
        /// </summary>
        public static string on_Monday {
            get {
                return ResourceManager.GetString("on Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期六 的本地化字符串。
        /// </summary>
        public static string on_Saturday {
            get {
                return ResourceManager.GetString("on Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期日 的本地化字符串。
        /// </summary>
        public static string on_Sunday {
            get {
                return ResourceManager.GetString("on Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期四 的本地化字符串。
        /// </summary>
        public static string on_Thursday {
            get {
                return ResourceManager.GetString("on Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期二 的本地化字符串。
        /// </summary>
        public static string on_Tuesday {
            get {
                return ResourceManager.GetString("on Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期三 的本地化字符串。
        /// </summary>
        public static string on_Wednesday {
            get {
                return ResourceManager.GetString("on Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一年多前 的本地化字符串。
        /// </summary>
        public static string OverAYearAgo {
            get {
                return ResourceManager.GetString("OverAYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}/{1} 的本地化字符串。
        /// </summary>
        public static string PartOfWhole {
            get {
                return ResourceManager.GetString("PartOfWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        public static string RepeatsEveryDay {
            get {
                return ResourceManager.GetString("RepeatsEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅一次 的本地化字符串。
        /// </summary>
        public static string RepeatsOnlyOnce {
            get {
                return ResourceManager.GetString("RepeatsOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作日 的本地化字符串。
        /// </summary>
        public static string RepeatsOnWeekdays {
            get {
                return ResourceManager.GetString("RepeatsOnWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周末 的本地化字符串。
        /// </summary>
        public static string RepeatsOnWeekends {
            get {
                return ResourceManager.GetString("RepeatsOnWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消 的本地化字符串。
        /// </summary>
        public static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载··· 的本地化字符串。
        /// </summary>
        public static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停 的本地化字符串。
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待 的本地化字符串。
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在上传··· 的本地化字符串。
        /// </summary>
        public static string StatusUploading {
            get {
                return ResourceManager.GetString("StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在等待··· 的本地化字符串。
        /// </summary>
        public static string StatusWaiting {
            get {
                return ResourceManager.GetString("StatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在等待··· 的本地化字符串。
        /// </summary>
        public static string StatusWaitingForExternalPower {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池电量不足 的本地化字符串。
        /// </summary>
        public static string StatusWaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("StatusWaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在等待连接 的本地化字符串。
        /// </summary>
        public static string StatusWaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("StatusWaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在等待建立 Wi-Fi 连接 的本地化字符串。
        /// </summary>
        public static string StatusWaitingForWiFi {
            get {
                return ResourceManager.GetString("StatusWaitingForWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择时间 的本地化字符串。
        /// </summary>
        public static string TimePickerTitle {
            get {
                return ResourceManager.GetString("TimePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时前 的本地化字符串。
        /// </summary>
        public static string XHoursAgo_2To4 {
            get {
                return ResourceManager.GetString("XHoursAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时前 的本地化字符串。
        /// </summary>
        public static string XHoursAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时前 的本地化字符串。
        /// </summary>
        public static string XHoursAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XHoursAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时前 的本地化字符串。
        /// </summary>
        public static string XHoursAgo_Other {
            get {
                return ResourceManager.GetString("XHoursAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟前 的本地化字符串。
        /// </summary>
        public static string XMinutesAgo_2To4 {
            get {
                return ResourceManager.GetString("XMinutesAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟前 的本地化字符串。
        /// </summary>
        public static string XMinutesAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟前 的本地化字符串。
        /// </summary>
        public static string XMinutesAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XMinutesAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟前 的本地化字符串。
        /// </summary>
        public static string XMinutesAgo_Other {
            get {
                return ResourceManager.GetString("XMinutesAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个月前 的本地化字符串。
        /// </summary>
        public static string XMonthsAgo_2To4 {
            get {
                return ResourceManager.GetString("XMonthsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个月前 的本地化字符串。
        /// </summary>
        public static string XMonthsAgo_5To12 {
            get {
                return ResourceManager.GetString("XMonthsAgo_5To12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒前 的本地化字符串。
        /// </summary>
        public static string XSecondsAgo_2To4 {
            get {
                return ResourceManager.GetString("XSecondsAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒前 的本地化字符串。
        /// </summary>
        public static string XSecondsAgo_EndsIn1Not11 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn1Not11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒前 的本地化字符串。
        /// </summary>
        public static string XSecondsAgo_EndsIn2To4Not12To14 {
            get {
                return ResourceManager.GetString("XSecondsAgo_EndsIn2To4Not12To14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒前 的本地化字符串。
        /// </summary>
        public static string XSecondsAgo_Other {
            get {
                return ResourceManager.GetString("XSecondsAgo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 周前 的本地化字符串。
        /// </summary>
        public static string XWeeksAgo_2To4 {
            get {
                return ResourceManager.GetString("XWeeksAgo_2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
